import {Providers} from '@/base';
import clsx from 'clsx';
import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';

import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={clsx(
          `${geistSans.variable} ${geistMono.variable} antialiased`,
          'bg-gray-100',
        )}>
        <Providers>
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  );
}
